/* Sofra Aile: anonymous, device-local web edition. No account or analytics. */
const storeKey='sofra-aile-v1';
const ui={page:'explore',query:'',category:'Tümü',limit:24,recipe:null,servings:2,method:-1};
let catalog={recipes:[],ingredients:{}};
let credits=[];
let state={basket:[],plan:null};
try{const saved=JSON.parse(localStorage.getItem(storeKey)||'{}');if(Array.isArray(saved.basket))state.basket=saved.basket;if(saved.plan&&typeof saved.plan==='object')state.plan=saved.plan;}catch{}
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const round=n=>Math.round((Number(n)||0)*10)/10;
const fmt=n=>new Intl.NumberFormat('tr-TR',{maximumFractionDigits:1}).format(round(n));
const img=p=>'./'+String(p||'').replace(/^\//,'');
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const recipe=id=>catalog.recipes.find(r=>r.id===id);
function save(){try{localStorage.setItem(storeKey,JSON.stringify(state));}catch{toast('Telefon depolama alanı dolu; liste kaydedilemedi.')}}
function toast(message){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.style.cssText='position:fixed;z-index:20;bottom:95px;left:50%;transform:translateX(-50%);background:#35251e;color:#fff;border-radius:12px;padding:11px 17px;box-shadow:0 6px 25px #0004;font-size:14px;min-width:180px;text-align:center';document.body.append(el)}el.textContent=message;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2800)}
function nav(){return `<nav class="nav" aria-label="Alt menü"><button data-page="explore" class="${ui.page==='explore'||ui.page==='detail'?'on':''}"><b>⌕</b>Tarifler</button><button data-page="plan" class="${ui.page==='plan'?'on':''}"><b>▦</b>Bugün</button><button data-page="basket" class="${ui.page==='basket'?'on':''}"><b>☑</b>Alışveriş <span>${state.basket.filter(x=>!x.done).length||''}</span></button></nav>`}
function header(){return `<header class="top"><div class="brandrow"><div class="brand"><span class="mark">S</span><strong>sofra.</strong></div><span class="sub">Giriş gerektirmez · ${catalog.recipes.length} tarif</span></div></header>`}
function footer(){return `<p class="foot">Tarif ve makro değerleri yaklaşık bilgi içindir. Fotoğraflar sunum veya teknik örneğidir. Alışveriş listen yalnızca bu telefonda saklanır. <a href="./kaynaklar.html">Görsel kaynakları</a></p>`}
function render(){const app=$('#app');app.className='app';app.innerHTML=(ui.page==='detail'?detail():header()+(ui.page==='explore'?explore():ui.page==='plan'?plan():basket()))+footer()+nav();bind();}
function explore(){let cats=['Tümü','Kahvaltı','Tavuk','Et','Sebze','Bakliyat','Balık','Tatlı','Ara öğün'];return `<h1 class="heading">Bugün ne pişirelim?</h1><p class="lead">Tarifini seç, adımlara bak, eksikleri listeye ekle.</p><input class="search" id="search" type="search" inputmode="search" placeholder="Yemek veya malzeme ara" aria-label="Tarif ara" value="${esc(ui.query)}"><div class="chips" aria-label="Kategoriler">${cats.map(c=>`<button class="chip ${ui.category===c?'on':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="results"></div>`}
function visibleRecipes(){const q=ui.query.trim().toLocaleLowerCase('tr-TR');return catalog.recipes.filter(r=>(ui.category==='Tümü'||r.category===ui.category)&&(!q||(r.title+' '+r.summary+' '+(r.items||[]).map(([id])=>catalog.ingredients[id]?.name||'').join(' ')).toLocaleLowerCase('tr-TR').includes(q)))}
function renderCards(){const box=$('#results');if(!box)return;const all=visibleRecipes();if(!all.length){box.innerHTML='<div class="empty">Bu aramada tarif bulamadık. Başka bir yemek veya malzeme dene.</div>';return}box.innerHTML=`<p class="meta">${all.length} tarif</p><div class="grid">${all.slice(0,ui.limit).map(r=>`<button class="card" data-recipe="${esc(r.id)}" aria-label="${esc(r.title)} tarifini aç"><img src="${img(r.image)}" alt="${esc(r.title)} için sunum görseli" loading="lazy"><div class="cardbody"><span class="category">${esc(r.category)}</span><h3>${esc(r.title)}</h3><span class="meta">${r.minutes} dk · ${r.servings} kişilik · ${fmt(r.macros?.kcal)} kcal/kişi</span></div></button>`).join('')}</div>${all.length>ui.limit?'<button class="more" id="more">Daha fazla tarif</button>':''}`;box.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>openDetail(b.dataset.recipe));const more=$('#more');if(more)more.onclick=()=>{ui.limit+=24;renderCards()}}
function openDetail(id){const r=recipe(id);if(!r)return;ui.page='detail';ui.recipe=id;ui.servings=r.servings;ui.method=-1;render();scrollTo(0,0)}
function selected(){const r=recipe(ui.recipe);if(!r)return null;return {r,m:ui.method<0?r:r.methods?.[ui.method]||r}}
function amount(id,n,servings,base){const unit=catalog.ingredients[id]?.unit||'g';return `${fmt(n*servings/base)} ${esc(unit)}`}
const equipment={hob:'Ocak',oven:'Fırın',airfryer:'Airfryer',microwave:'Mikrodalga',blender:'Blender'};
function detail(){const x=selected();if(!x)return '';const {r,m}=x;const base=r.servings||1;const steps=m.steps||[];const photos=new Map((m.stepPhotos||r.stepPhotos||[]).map(p=>[p.step,p]));const credit=credits.find(c=>c.recipeId===r.id);return `<div class="detailtop"><img class="hero" src="${img(r.image)}" alt="${esc(r.title)} sunum görseli"><button class="back" id="back">‹ Tariflere dön</button></div><span class="category" style="margin-top:18px">${esc(r.category)}</span><h1 class="detailtitle">${esc(r.title)}</h1><p class="lead">${esc(r.summary)}</p><p class="meta">${m.minutes||r.minutes} dakika · ${esc((m.equipment||r.equipment||[]).map(x=>equipment[x]||x).join(', ')||'Ekipman belirtilmedi')}</p><div class="nutrients">${[['Kalori','kcal','kcal'],['Protein','protein','g'],['Karbonhidrat','carbs','g'],['Yağ','fat','g']].map(([label,k,u])=>`<div class="nutrient"><strong>${fmt(m.macros?.[k]??r.macros?.[k])}</strong>${label} ${u}</div>`).join('')}</div><p class="meta">Yaklaşık değerler kişi başına; malzeme ve porsiyon değişince yeniden hesaplanmaz.</p>${r.methods?.length?`<div class="chips" aria-label="Pişirme yöntemi"><button class="chip ${ui.method<0?'on':''}" data-method="-1">Ana tarif</button>${r.methods.map((mm,i)=>`<button class="chip ${ui.method===i?'on':''}" data-method="${i}">${esc(mm.name)}</button>`).join('')}</div>`:''}<section class="panel"><div class="servings"><h2>Malzemeler</h2><div class="stepper" aria-label="Kişi sayısı"><button id="minus" aria-label="Kişi sayısını azalt">−</button><strong>${ui.servings} kişi</strong><button id="plus" aria-label="Kişi sayısını artır">+</button></div></div><ul class="list">${(m.items||r.items||[]).map(([id,n])=>`<li><span>${esc(catalog.ingredients[id]?.name||id)}</span><span class="amount">${amount(id,n,ui.servings,base)}</span></li>`).join('')}</ul><button class="primary" id="add" style="width:100%;margin-top:14px">Malzemeleri alışverişe ekle</button></section><section class="panel"><h2>Birlikte pişirelim</h2>${steps.map((step,i)=>{const p=photos.get(i);return `<div class="step"><div class="stephead">${i+1}. adım</div><p>${esc(step)}</p>${p?`<img src="${img(p.image)}" alt="${esc(p.alt||p.caption||'Hazırlık görseli')}" loading="lazy"><span class="caption">${esc(p.caption||'Teknik görsel')}</span>`:''}</div>`}).join('')}</section>${credit?`<p class="bottomnote">Kapak: ${esc(credit.artist)} · ${esc(credit.license)} · <a href="${esc(credit.sourceUrl)}" target="_blank" rel="noopener noreferrer">Kaynak</a>. ${esc(credit.caption)}</p>`:'<p class="bottomnote">Kapak görseli temsili sunum örneğidir.</p>'}`}
function addItems(items,servings,base){for(const [id,n] of items){const qty=round(n*servings/base);const old=state.basket.find(x=>x.id===id);if(old){old.qty=round(old.qty+qty);old.done=false}else state.basket.push({id,qty,done:false})}save();toast('Malzemeler listeye eklendi');render()}
const slots=[['breakfast','Kahvaltı',['Kahvaltı']],['lunch','Öğle',['Tavuk','Et','Vejetaryen','Bakliyat','Balık']],['dinner','Akşam',['Çorba','Sebze','Salata','Hindi','Ana yemek']],['snack','Ara öğün',['Ara öğün']]];
function picks(slot,exclude=[]){const pool=catalog.recipes.filter(r=>slot[2].includes(r.category)&&Number(r.macros?.kcal)>=120&&Number(r.macros?.kcal)<=800&&!exclude.includes(r.id));return pool[Math.floor(Math.random()*pool.length)]}
function ensurePlan(){if(state.plan?.date===today()&&slots.every(([k])=>recipe(state.plan[k])))return;const p={date:today()};for(const [k,,] of slots){p[k]=picks(slots.find(s=>s[0]===k),Object.values(p))?.id}state.plan=p;save()}
function plan(){ensurePlan();const rs=slots.map(([k])=>recipe(state.plan[k])).filter(Boolean);const total=rs.reduce((s,r)=>{for(const k of ['kcal','protein','carbs','fat'])s[k]+=Number(r.macros?.[k]||0);return s},{kcal:0,protein:0,carbs:0,fat:0});return `<h1 class="heading">Bugün için örnek menü</h1><p class="lead">İstersen öğünleri değiştir. Bu menü kişisel sağlık hedefi veya alerji kontrolü yapmaz; malzemeleri incele.</p><div class="panel">${slots.map(([k,label])=>{const r=recipe(state.plan[k]);return r?`<div class="planrow"><img src="${img(r.image)}" loading="lazy" alt=""><div class="copy"><span class="category">${label}</span><strong>${esc(r.title)}</strong><span class="meta">${fmt(r.macros?.kcal)} kcal · ${fmt(r.macros?.protein)} g protein</span></div><button data-swap="${k}" aria-label="${label} öğününü değiştir">Değiştir</button></div>`:''}).join('')}<div class="nutrients">${[['Enerji','kcal','kcal'],['Protein','protein','g'],['Karb.','carbs','g'],['Yağ','fat','g']].map(([label,k,u])=>`<div class="nutrient"><strong>${fmt(total[k])}</strong>${label} ${u}</div>`).join('')}</div><div class="buttonrow"><button class="secondary" id="newplan">Yeni menü</button><button class="primary" id="planadd">Eksikleri listeye ekle</button></div></div><p class="bottomnote">Hesap yaklaşık ve her tariften bir kişilik porsiyon içindir. Sağlık veya diyet önerisi değildir.</p>`}
function basket(){return `<h1 class="heading">Alışveriş listem</h1><p class="lead">Tariften eklediklerini alırken işaretle. Liste sadece bu telefonda kalır.</p>${state.basket.length?`<div class="panel">${state.basket.map((it,i)=>`<div class="basketrow ${it.done?'done':''}"><input type="checkbox" data-check="${i}" ${it.done?'checked':''} aria-label="${esc(catalog.ingredients[it.id]?.name||it.id)} alındı"><span class="itemname">${esc(catalog.ingredients[it.id]?.name||it.id)}</span><strong>${fmt(it.qty)} ${esc(catalog.ingredients[it.id]?.unit||'g')}</strong><button data-remove="${i}" aria-label="Ürünü sil">×</button></div>`).join('')}</div><button class="secondary" id="clearchecked">İşaretlenenleri temizle</button>`:'<div class="empty">Listen boş. Bir tarifi açıp malzemeleri ekleyebilirsin.</div>'}`}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{ui.page=b.dataset.page;render();scrollTo(0,0)});if(ui.page==='explore'){const input=$('#search');input.oninput=()=>{ui.query=input.value;ui.limit=24;renderCards()};document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{ui.category=b.dataset.category;ui.limit=24;render()});renderCards()}if(ui.page==='detail'){const x=selected();$('#back').onclick=()=>{ui.page='explore';render();scrollTo(0,0)};$('#minus').onclick=()=>{if(ui.servings>1){const y=scrollY;ui.servings--;render();scrollTo(0,y)}};$('#plus').onclick=()=>{if(ui.servings<12){const y=scrollY;ui.servings++;render();scrollTo(0,y)}};document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{ui.method=Number(b.dataset.method);const y=scrollY;render();scrollTo(0,y)});$('#add').onclick=()=>addItems(x.m.items||x.r.items,ui.servings,x.r.servings||1)}if(ui.page==='plan'){document.querySelectorAll('[data-swap]').forEach(b=>b.onclick=()=>{const k=b.dataset.swap;const s=slots.find(s=>s[0]===k);state.plan[k]=picks(s,Object.values(state.plan))?.id||state.plan[k];save();render()});$('#newplan').onclick=()=>{state.plan=null;ensurePlan();render()};$('#planadd').onclick=()=>{for(const [k] of slots){const r=recipe(state.plan[k]);if(r)addItemsSilent(r.items,1,r.servings||1)}save();toast('Günlük malzemeler eklendi');render()}}if(ui.page==='basket'){document.querySelectorAll('[data-check]').forEach(b=>b.onchange=()=>{state.basket[Number(b.dataset.check)].done=b.checked;save();render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.basket.splice(Number(b.dataset.remove),1);save();render()});const clear=$('#clearchecked');if(clear)clear.onclick=()=>{state.basket=state.basket.filter(x=>!x.done);save();render()}}}
function addItemsSilent(items,servings,base){for(const [id,n] of items){const qty=round(n*servings/base);const old=state.basket.find(x=>x.id===id);if(old){old.qty=round(old.qty+qty);old.done=false}else state.basket.push({id,qty,done:false})}}
(async()=>{try{const [a,b]=await Promise.all([fetch('./catalog.json'),fetch('./photo-credits.json')]);if(!a.ok)throw Error('Tarif verisi yüklenemedi');catalog=await a.json();if(b.ok)credits=await b.json();if(catalog.recipes.length!==458)throw Error('Tarif listesi eksik');render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(e){$('#app').innerHTML=`<div class="boot"><span class="mark">S</span><h1>Tarifler açılamadı</h1><p>İnternet bağlantını kontrol edip sayfayı yenile.</p><button class="primary" onclick="location.reload()">Tekrar dene</button></div>`;console.error(e)}})();
